# Generated by Django 3.2.5 on 2021-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0002_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
