# Generated by Django 3.2.5 on 2021-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0007_alter_cart_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(to='dadova.Review'),
        ),
    ]
