# Generated by Django 3.2.5 on 2021-10-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0009_alter_cart_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(blank=True, to='dadova.Course'),
        ),
    ]
