# Generated by Django 3.2.5 on 2021-10-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0011_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.BigIntegerField(blank=True, verbose_name='Баланс:'),
        ),
    ]
