# Generated by Django 3.2.5 on 2021-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0012_alter_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.BigIntegerField(max_length=255, verbose_name='Цена'),
        ),
    ]
