# Generated by Django 3.2.5 on 2021-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0013_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.BigIntegerField(verbose_name='Цена'),
        ),
    ]
