# Generated by Django 3.2.5 on 2021-10-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dadova', '0014_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_bought',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
