# Generated by Django 3.2.5 on 2021-10-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadova', '0016_boughtedcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_bought',
        ),
    ]
